config/routes.rb
Rails.application.routes.draw do
  resources :insurance_certificates

  resources :settle_agrees

  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  root 'settle_agrees#new'

end

app/models/insurance_certificate.rb
class InsuranceCertificate < ActiveRecord::Base
end

app/models/settle_agree.rb
class SettleAgree < ActiveRecord::Base
	validates :plaintiff, :defendant, :settle_amount, :pay_date, :court, :confidential, :choice_of_law, 
	:signature_block, :case_type, :notice_to, :indemnity, :required, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/insurance_certificates_controller.rb
class InsuranceCertificatesController < ApplicationController
  before_action :set_insurance_certificate, only: [:show, :edit, :update, :destroy]

  # GET /insurance_certificates
  # GET /insurance_certificates.json
  def index
    @insurance_certificates = InsuranceCertificate.all
  end

  # GET /insurance_certificates/1
  # GET /insurance_certificates/1.json
  def show
  end

  # GET /insurance_certificates/new
  def new
    @insurance_certificate = InsuranceCertificate.new
  end

  # GET /insurance_certificates/1/edit
  def edit
  end

  # POST /insurance_certificates
  # POST /insurance_certificates.json
  def create
    @insurance_certificate = InsuranceCertificate.new(insurance_certificate_params)

    respond_to do |format|
      if @insurance_certificate.save
        format.html { redirect_to @insurance_certificate, notice: 'Insurance certificate was successfully created.' }
        format.json { render :show, status: :created, location: @insurance_certificate }
      else
        format.html { render :new }
        format.json { render json: @insurance_certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurance_certificates/1
  # PATCH/PUT /insurance_certificates/1.json
  def update
    respond_to do |format|
      if @insurance_certificate.update(insurance_certificate_params)
        format.html { redirect_to @insurance_certificate, notice: 'Insurance certificate was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurance_certificate }
      else
        format.html { render :edit }
        format.json { render json: @insurance_certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurance_certificates/1
  # DELETE /insurance_certificates/1.json
  def destroy
    @insurance_certificate.destroy
    respond_to do |format|
      format.html { redirect_to insurance_certificates_url, notice: 'Insurance certificate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurance_certificate
      @insurance_certificate = InsuranceCertificate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurance_certificate_params
      params.require(:insurance_certificate).permit(:form_number, :insuror, :occurrence_limit, :aggregate_limit, :named_insured, :policy_start_date, :policy_end_date, :certificate_holder, :additional_insured, :number_of_certificates_issued)
    end
end

app/controllers/settle_agrees_controller.rb
class SettleAgreesController < ApplicationController
  before_action :set_settle_agree, only: [:show, :edit, :update, :destroy]

  # GET /settle_agrees
  # GET /settle_agrees.json
  def index
    @settle_agrees = SettleAgree.all
  end

  # GET /settle_agrees/1
  # GET /settle_agrees/1.json
  def show
  end

  # GET /settle_agrees/new
  def new
    @settle_agree = SettleAgree.new
  end

  # GET /settle_agrees/1/edit
  def edit
  end

  # POST /settle_agrees
  # POST /settle_agrees.json
  def create
    @settle_agree = SettleAgree.new(settle_agree_params)

    respond_to do |format|
      if @settle_agree.save
        format.html { redirect_to @settle_agree, notice: 'Settle agree was successfully created.' }
        format.json { render :show, status: :created, location: @settle_agree }
      else
        format.html { render :new }
        format.json { render json: @settle_agree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settle_agrees/1
  # PATCH/PUT /settle_agrees/1.json
  def update
    respond_to do |format|
      if @settle_agree.update(settle_agree_params)
        format.html { redirect_to @settle_agree, notice: 'Settle agree was successfully updated.' }
        format.json { render :show, status: :ok, location: @settle_agree }
      else
        format.html { render :edit }
        format.json { render json: @settle_agree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settle_agrees/1
  # DELETE /settle_agrees/1.json
  def destroy
    @settle_agree.destroy
    respond_to do |format|
      format.html { redirect_to settle_agrees_url, notice: 'Settle agree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_settle_agree
      @settle_agree = SettleAgree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def settle_agree_params
      params.require(:settle_agree).permit(:plaintiff, :defendant, :settle_amount, :pay_date, :court, :confidential, :choice_of_law, :signature_block, :case_type, :notice_to, :indemnity, :required, :intro_text)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/insurance_certificates_helper.rb
module InsuranceCertificatesHelper
end

app/helpers/settle_agrees_helper.rb
module SettleAgreesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/insurance_certificates/_form.html.erb
<%= form_for(@insurance_certificate) do |f| %>
  <% if @insurance_certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insurance_certificate.errors.count, "error") %> prohibited this insurance_certificate from being saved:</h2>

      <ul>
      <% @insurance_certificate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :form_number %><br>
    <%= f.number_field :form_number %>
  </div>
  <div class="field">
    <%= f.label :insuror %><br>
    <%= f.text_field :insuror %>
  </div>
  <div class="field">
    <%= f.label :occurrence_limit %><br>
    <%= f.number_field :occurrence_limit %>
  </div>
  <div class="field">
    <%= f.label :aggregate_limit %><br>
    <%= f.number_field :aggregate_limit %>
  </div>
  <div class="field">
    <%= f.label :named_insured %><br>
    <%= f.text_field :named_insured %>
  </div>
  <div class="field">
    <%= f.label :policy_start_date %><br>
    <%= f.date_select :policy_start_date %>
  </div>
  <div class="field">
    <%= f.label :policy_end_date %><br>
    <%= f.date_select :policy_end_date %>
  </div>
  <div class="field">
    <%= f.label :certificate_holder %><br>
    <%= f.text_field :certificate_holder %>
  </div>
  <div class="field">
    <%= f.label :additional_insured %><br>
    <%= f.text_field :additional_insured %>
  </div>
  <div class="field">
    <%= f.label :number_of_certificates_issued %><br>
    <%= f.number_field :number_of_certificates_issued %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insurance_certificates/edit.html.erb
<h1>Editing insurance_certificate</h1>

<%= render 'form' %>

<%= link_to 'Show', @insurance_certificate %> |
<%= link_to 'Back', insurance_certificates_path %>

app/views/insurance_certificates/index.html.erb
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.0/css/jquery.dataTables.css">
<div class="container">
  <div class="row">
    <div class="col-lg-12" >
<h1>Insurance Certificates</h1>
<div class="table-responsive">
<table id="certTable" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Form number</th>
      <th>Insuror</th>
      <th>Occurrence limit</th>
      <th>Aggregate limit</th>
      <th>Named insured</th>
      <th>Policy start date</th>
      <th>Policy end date</th>
      <th>Certificate holder</th>
      <th>Additional insured</th>
      <th>Number of certificates issued</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurance_certificates.each do |insurance_certificate| %>
      <tr>
        <td><%= insurance_certificate.form_number %></td>
        <td><%= insurance_certificate.insuror %></td>
        <td><%= insurance_certificate.occurrence_limit %></td>
        <td><%= insurance_certificate.aggregate_limit %></td>
        <td><%= insurance_certificate.named_insured %></td>
        <td><%= insurance_certificate.policy_start_date %></td>
        <td><%= insurance_certificate.policy_end_date %></td>
        <td><%= insurance_certificate.certificate_holder %></td>
        <td><%= insurance_certificate.additional_insured %></td>
        <td><%= insurance_certificate.number_of_certificates_issued %></td>
        <td><%= link_to 'Show', insurance_certificate %></td>
        <td><%= link_to 'Edit', edit_insurance_certificate_path(insurance_certificate) %></td>
        <td><%= link_to 'Destroy', insurance_certificate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Insurance Certificate', new_insurance_certificate_path %>
</div></div>

</div>
</div>
<script src ="//cdn.datatables.net/1.10.0/js/jquery.dataTables.js"></script>

<script>
$(document).ready(function(){
    $('#certTable').dataTable();
});

</script>

app/views/insurance_certificates/new.html.erb
<h2>Create A New Insurance Certificate</h2>

<%= render 'form' %>

<%= link_to 'Back', insurance_certificates_path %>

app/views/insurance_certificates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Form number:</strong>
  <%= @insurance_certificate.form_number %>
</p>

<p>
  <strong>Insuror:</strong>
  <%= @insurance_certificate.insuror %>
</p>

<p>
  <strong>Occurrence limit:</strong>
  <%= @insurance_certificate.occurrence_limit %>
</p>

<p>
  <strong>Aggregate limit:</strong>
  <%= @insurance_certificate.aggregate_limit %>
</p>

<p>
  <strong>Named insured:</strong>
  <%= @insurance_certificate.named_insured %>
</p>

<p>
  <strong>Policy start date:</strong>
  <%= @insurance_certificate.policy_start_date %>
</p>

<p>
  <strong>Policy end date:</strong>
  <%= @insurance_certificate.policy_end_date %>
</p>

<p>
  <strong>Certificate holder:</strong>
  <%= @insurance_certificate.certificate_holder %>
</p>

<p>
  <strong>Additional insured:</strong>
  <%= @insurance_certificate.additional_insured %>
</p>

<p>
  <strong>Number of certificates issued:</strong>
  <%= @insurance_certificate.number_of_certificates_issued %>
</p>

<%= link_to 'Edit', edit_insurance_certificate_path(@insurance_certificate) %> |
<%= link_to 'Back', insurance_certificates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formcontract</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.0/css/jquery.dataTables.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

</html>

app/views/settle_agrees/edit.html.erb
<h1>Editing settle_agree</h1>

<%= render 'form' %>

<%= link_to 'Show', @settle_agree %> |
<%= link_to 'Back', settle_agrees_path %>

app/views/settle_agrees/index.html.erb
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.0/css/jquery.dataTables.css">


<div class="container">
  <div class="row">
    <div class="col-lg-12" >
<h3 stye="text-align:center">My Agreements</h3>
<div class="table-responsive">
<table id="myTable" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Plaintiff</th>
      <th>Defendant</th>
      <th>Settle amount</th>
      <th>Pay date</th>
      <th>Court</th>
      <th>Confidential</th>
      <th>Choice of law</th>
      <th>Signature block</th>
      <th>Case type</th>
      <th>Notice to</th>
      <th>Indemnity</th>
      <th>Required</th>
      <th Options</th>
    </tr>
  </thead>

  <tbody>
    <% @settle_agrees.each do |settle_agree| %>
      <tr>
        <td><%= settle_agree.plaintiff %></td>
        <td><%= settle_agree.defendant %></td>
        <td><%= settle_agree.settle_amount %></td>
        <td><%= settle_agree.pay_date %></td>
        <td><%= settle_agree.court %></td>
        <td><%= settle_agree.confidential %></td>
        <td><%= settle_agree.choice_of_law %></td>
        <td><%= settle_agree.signature_block %></td>
        <td><%= settle_agree.case_type %></td>
        <td><%= settle_agree.notice_to %></td>
        <td><%= settle_agree.indemnity %></td>
        <td><%= settle_agree.required %></td>
        <td><%= link_to 'Show | ', settle_agree %>
        <%= link_to 'Edit |', edit_settle_agree_path(settle_agree) %>
        <%= link_to 'Destroy', settle_agree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>
</div>
<%= link_to 'New Form', new_settle_agree_path, :style=>"color:white; background-color:black; padding:10px" %>
<br>
</div>
</div>
</div>



<script src ="//cdn.datatables.net/1.10.0/js/jquery.dataTables.js"></script>

<script>
$(document).ready(function(){
    $('#myTable').dataTable();
});

</script>

app/views/settle_agrees/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-8" style="border-right:1px solid lightgray" >
			
<h3>Create New Settlement Agreement</h3>
<hr>
<%= render 'form' %>

<%= link_to 'Back', settle_agrees_path %>

</div>
<div class="col-xs-4 clearfix" >
	
	<h3>Options</h3>
	<br class="visible-xs">
	
<li><a href="#">Settings </a</li>
<li><a href="#">Add File </a</li>
<li><a href="#">Messages </a</li>
<li><a href="#">Cases </a</li>
<li><a href="#">Deadlines </a></li>
<hr>
<h3>My Form Library</h3>
	<br class="visible-xs">
<li><%=link_to 'Directory', settle_agrees_path %>	</lI>
<li><%=link_to 'Insurance Certificates', insurance_certificates_path %>	</lI>
<li><a href="#">Contracts</a></li>
<li><a href="#"><a>Lawsuits</li>
<li><a href="#"><a>Policies</li>
<li><a href="#"><a>Term Sheets</li>
<li><a href="#"><a>Create New</li>
	
<hr>

	</div>
</div>
</div>

app/views/settle_agrees/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container" id="this">
  <div class="row">
    <div class="col-xs-12" style="border-right:1px solid lightgray" >
<h3>Settlement Agreement</h3>
<h4>Term Sheet</h4>
<hr>


<%=@settle_agree.intro_text %> 

</p>
<p>This agreement is entered into by <strong><%= @settle_agree.plaintiff %></strong> and <strong><%= @settle_agree.defendant %>.</strong>  The parties agree that the following shall terms apply:

<p>
  The parties agree to a settlement payment amount of: $<strong>
  <%=@settle_agree.settle_amount %></strong>
</p>

<p>
  Payment shall be made on or before:<strong>
  <%= @settle_agree.pay_date %>
</p></strong>

<p>
  This settlement will include a release of all claims related to litigation between the parties pending in <strong>
  <%= @settle_agree.court %></strong>
</p>

<p>
 The parties agree to keep the settlement agreement confidential:<strong>
  <%= @settle_agree.confidential %></strong>
</p

<p>
  The agreement will be subject to the law of the following jurisdiction <strong>
  <%= @settle_agree.choice_of_law %></strong>
</p>

<p>
 Notice to parties will be provided to:<strong>
  <%= @settle_agree.notice_to %> </strong>
</p>

<p>
  Indemnity language (if any) will cover:<strong>
  <%= @settle_agree.indemnity %></strong>
</p>
<p>
  Signatures appear here:<strong>
  <%= @settle_agree.signature_block %></strong>
</p>
<p>Date:</p>
<hr>
<%= link_to 'Edit', edit_settle_agree_path(@settle_agree) %> |
<%= link_to 'Back | ', settle_agrees_path %>
<a onClick="window.print()">Print | </a>
<a href="#">Download | </a>
<%= link_to 'Home', root_url %>

</div>
</div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>